name: helloservice
# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kamsafe
    password: 7glNs5Q^&fQBDoXDpG
    url: jdbc:mysql://39.98.162.159:3306/kamsafe_1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    
# 打印sql
logging:
  level:
    com.qiangqiang.helloservice.mapper: debug
